config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "bookmarks#index", as: :authenticated_root
  end

  root "pages#home"

  get "/erase", to: "recipes#erase"
  # get "/listar_modelos_gemini", to: "recipes#listar_modelos_gemini"

  resources :ingredients
  resources :recipes, only: [:index, :show, :new, :create, :update] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :recipes do
    resources :comments, only: [:create, :destroy]
  end

  resources :comments, only: [:destroy]
  resources :bookmarks, only: [:index, :new, :create, :show, :destroy]
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :destroy]

  def index
    @bookmarks = current_user.bookmarks.joins(:recipe).order('recipes.id DESC')
    if params[:done].present?
      @bookmarks = @bookmarks.where(recipes: { done: params[:done] })
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
    @recipe = @bookmark.recipe
    @comments = @recipe.comments
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path, notice: "Recipe removed."
  end


  def create

    raise
        # @bookmark = Bookmark.new(user: current_user, recipe: @recipe)

    # if  @bookmark.save
    #   flash[:alert]="Recipe saved in the history !"
    #   redirect_to request.referer
    # end
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id)
  end
end

app/views/bookmarks/index.html.erb
<%# ----------------------- Header ------------------------------------------ %>


<div class="d-flex justify-content-between align-items-center w-100">
  <div class="p-4 w-100 navbar-lewagon" style="background-color: #5edc9b; display: flex; justify-content: center; align-items: center; opacity: 1; position: relative; border-radius: 0 0 20px 20px;">
    <h1 class="text-center main-header" style="margin: 0;">Welcome <%= current_user.email%></h1>
  </div>
</div>



<%# ---------------- Button New Meal ---------------------------------------- %>

<div class="text-center">
  <%= link_to '+ NEW MEAL', ingredients_path, class: "btn w-75 rounded-5
   py-2 mt-3 shadow", style: "background-color: #5edc9b; opacity: 1; border: 3px solid #dbcbb3;" %>
</div>


<%# ---------------- Body --------------------------------------------------- %>

<div class="container-fluid my-3">
  <div class="card mx-auto shadow" style="max-width: 600px; border-radius: 24px; background-color:#fd8442; opacity: 1;">
    <div class="card-body">
      <h2 class="text-center mb-3">My History</h2>

      <input type="text" id="recipeList" onkeyup="myFunction()" placeholder="Search for recipes..">

      <ul id="mytestUL">
        <% if @bookmarks.present? %>
          <% @bookmarks.each do |bookmark| %>
            <li class="mb-3">
              <%= link_to bookmark_path(bookmark), class: 'd-flex justify-content-between align-items-center btn btn-link rounded-3' do %>
                <!-- Title -->
                <span><%= bookmark.recipe.title %></span>

                <!-- Done status icon -->
                <% if bookmark.recipe.done == true %>
                  <span class="ms-3"><i class="fa-solid fa-square-check fa-xl"></i></span>
                <% else %>
                  <span class="ms-3"><i class="fa-solid fa-bookmark fa-xl"></i></span>
                <% end %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <div class="d-flex justify-content-center align-items-center" style="height: 50px;">
            <p class="card-text">No recipe yet.</p>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%# ---------------- Script ------------------------------------------------- %>

<script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('recipeList');
  filter = input.value.toUpperCase();
  ul = document.getElementById("mytestUL");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>

app/views/bookmarks/new.html.erb
<h1>Add a new recipe</h1>

app/views/bookmarks/show.html.erb
  <%# -------------------- Header ------------------ %>

<div class="mb-3 p-4" style="background-color: #5edc9b; opacity: 1; display:
flex; justify-content: center; align-items: center; position: relative; border-radius: 0 0 20px 20px;">

  <%= link_to bookmarks_path, style: "position: absolute; left: 20px;" do %>
    <i class="fa-regular fa-circle-left fa-2xl" style="color: #000000;"></i>
  <% end %>

  <h1 class="text-center" style="margin: 0;">YOUR PREVIOUS RECIPE</h1>

</div>


  <%# -------------------- Recipe ------------------ %>

<div class="border m-3 p-3 bg-light" style="border-radius: 15px !important">

  <% if @bookmark.recipe.present? %>
    <h2 class="text-center fs-4 border-bottom pb-2"><strong><%= @bookmark.recipe.title %></strong></h2>

    <p><i class="fa-solid fa-stopwatch fa-lg m-2"></i> <%= @bookmark.recipe.prep_time %></p>
    <p><i class="fa-solid fa-utensils fa-lg m-2"></i> <%= @bookmark.recipe.servings %></p>
    <p><strong>Step-by-step:</strong></p>
    <ul>
    <% @bookmark.recipe.instructions.split(/\n/).each do |instruction|%>
      <li> <%=instruction %></li>
    <% end %>
    </ul>

    <% if @bookmark.recipe.rating.present? %>
  <p>
    <strong>Rating :</strong>
    <%= ('⭐' * @bookmark.recipe.rating).html_safe %>
  </p>
<% end %>
  <% else %>
    <p>No recipe data available.</p>
  <% end %>


  <%# -------------------- Button "I did it"------------------ %>

  <div class="d-flex justify-content-end m-3">
    <% if @recipe.done == false %>
      <%= button_to 'I did it!',
        { controller: "recipes",
          action: "update",
          id: @recipe.id,
          recipe: { done: true } },
        method: :patch,
        class: "btn btn-success mx-1 rounded-pill",
        data: { turbo: true } %>
    <% end %>
  </div>

</div>


  <%# -------------------- Comment ------------------------------------------ %>

<div class="border mx-3 mb-3 p-3 bg-light" style="border-radius: 15px !important">

  <h2>Comment :</h2>

  <% if @comments.any? %>
    <ul>
      <% @comments.each do |comment| %>
        <li>
          <strong><%= comment.created_at.strftime("%d %b %Y, %H:%M") %></strong> :
          <div class="d-inline-flex align-items-center">
            <%= comment.content %>
            <%= button_to "",
                          [comment.recipe, comment],
                          method: :delete,
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this comment?" },
                          class: "btn btn--light fa-regular fa-trash-can mx-1" %>
            </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No comments for this recipe.</p>
  <% end %>

  <%# -------------------- Button add comment ------------------------------- %>
  <div class="border-0 bg-transparent" style="width: 200px;">
    <%= link_to new_recipe_comment_path(@recipe) do %>
      <div class="d-flex">
       <i class="fa-regular fa-message fs-1" style="cursor: pointer;"></i> <p class="fa-2x pb-3">+</p>
      </div>
    <% end %>
  </div>

</div>


<div class="d-flex justify-content-center gap-2 m-2">
  <%# -------------------- Button delete ------------------------------------ %>
     <%= button_to "I won't cook It anymore!",
                bookmark_path(@bookmark),
                method: :delete,
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-danger rounded-pill" %>
</div>