config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "bookmarks#index", as: :authenticated_root
  end

  root "pages#home"

  get "/erase", to: "recipes#erase"
  # get "/listar_modelos_gemini", to: "recipes#listar_modelos_gemini"

  resources :ingredients
  resources :recipes, only: [:index, :show, :new, :create, :update] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :recipes do
    resources :comments, only: [:create, :destroy]
  end

  resources :comments, only: [:destroy]
  resources :bookmarks, only: [:index, :new, :create, :show, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.new(recipe: @recipe)
    @comments = @recipe.comments
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comments = @recipe.comments
    @comment = Comment.new(comment_params)
    @comment.recipe = @recipe

    if @comment.save
      redirect_to new_recipe_comment_path, notice: 'Comment added !'
    else
      flash.now[:alert] = 'Error. Could not create the comment.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back fallback_location: recipe_path(@comment.recipe), notice: "Comment was deleted."
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_form.html.erb
<%# Comment form %>

<%= simple_form_for [recipe,comment], data: { controller: "form-submit" } do |form| %>

  <div class="my-3">
    <%= form.input :content, label: "Your comment"%>
  </div>


  <%# Save %>

  <%= form.submit "Save Comment", class: "btn btn-success rounded-pill" %>
<% end %>

app/views/comments/_form_rating.html.erb
<%= simple_form_for recipe, data: { controller: "form-submit" } do |form| %>

<div class="my-3">
  <%= form.select :rating, (1..5).to_a, {},
        data: { controller: "star-rating", action: "change->form-submit#submit" },
        # data: { controller: "star-rating", action: "click->submit#submit" },
        class: "form-select",
        name: "recipe[rating]" %>
</div>

  <%#= form.submit "Rate !", class: "btn btn-success rounded-pill" %>
<% end %>

app/views/comments/new.html.erb
  <%# ------------------------ Header --------------------------------------- %>

<div class="mb-3 p-4" style="background-color: #5edc9b; opacity: 1; display: flex; justify-content: center; align-items: center; position: relative; border-radius: 0 0 20px 20px;">
  <%= link_to request.referer, style: "position: absolute; left: 20px;" do %>
    <i class="fa-regular fa-circle-left fa-2xl" style="color: #000000;"></i>
  <% end %>
  <h1 class="text-center" style="margin: 0;">COMMENT / SHARE</h1>
</div>

  <%# -------------------- Recipe details------------------------------------ %>

<div class="border mx-3 p-3 mb-3 bg-light" style="border-radius: 15px !important">
  <p><strong><%= @recipe.title %></strong></p>
  <p><i class="fa-solid fa-stopwatch fa-lg m-s-5 my-2"></i>   <%= @recipe.prep_time %></p>
  <p><i class="fa-solid fa-utensils fa-lg m-s-5 my-2"></i>   <%= @recipe.servings %></p>
</div>


<div data-controller="insert-in-list">
  <div class="border mx-3 p-3 bg-light" style="border-radius: 15px !important">
    <p>Rate this meal ! <%= render "form_rating", recipe: @recipe %></p>
    <p>Comments :</p>

    <div>

      <% if @comments.any? %>
        <ul>
          <% @comments.each do |comment| %>
            <li>
              <div class="d-flex justify-content-between">
                <strong><%= comment.content %></strong> - <small><%= comment.created_at.strftime("%d %b %Y") %></small>
                <%= button_to "",
                              [comment.recipe, comment],
                              method: :delete,
                              data: { turbo_method: :delete},
                              class: "btn btn--light fa-regular fa-trash-can mx-1" %>

              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No comment for this recipe.</p>
      <% end %>

    </div>
  </div>



  <div class="d-flex justify-content-center">


  <%# --------------------------- Comment ----------------------------------- %>
    <div data-controller="toggle" class="m-3">
      <button data-action="click->toggle#fire" class="border-0 bg-white p-3 rounded-pill">
        <i class="fa-regular fa-message fs-1" style="cursor: pointer;"></i>
      </button>

      <div data-toggle-target="togglableElement" class="d-none">
        <%= render "form", comment: @comment, recipe: @recipe %>
      </div>
    </div>

    <%# ----------------------- Share ----------------------------------------- %>

    <div class="mt-3 me-3">
        <button id="share-button" class="border-0 bg-white p-3 rounded-pill" data-url="<%= recipe_url(@comment.recipe) %>">
          <i class="fa-solid fa-share-nodes fs-1"></i>
        </button>
      </div>

  </div>
</div>

  <%# ----------- Back to home page --------------- %>
<div class="d-flex justify-content-center">
    <%= link_to "Skip to my next meal", erase_path, class: "btn btn-info rounded-pill mx-5", style:"opacity: 1; background-color: #fd8442; border: 3px solid #dbcbb3;" %>
</div>

  <%# ----------- Logo --------------- %>

<div class="my-3" style="width: 200px; height: 200px; margin: 0 auto; border: 5px solid white; border-radius: 50%; display: flex; justify-content: center; align-items: center;">
  <%= image_tag 'robot_logo.png', alt: 'Description of the image', class: "rounded-pill" %>
</div>



  <%# -------------------- Script ------------------ %>

<script>
  const button = document.getElementById("share-button")
  button.addEventListener("click", function () {
    const message = `"Check out this recipe I just tried!" ${button.dataset.url}`;
    const whatsappURL = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
    window.open(whatsappURL, "_blank");
  });
</script>

app/views/comments/show.html.erb
<h1><%= @bookmark.recipe.title %> - Comments</h1>

<% @bookmark.comments.each do |comment| %>
  <div>
    <p><strong><%= comment.user.email %>:</strong> <%= comment.text %></p>
  </div>
<% end %>

<%= link_to 'Add a new comment', new_bookmark_comment_path(@bookmark) %>