config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "bookmarks#index", as: :authenticated_root
  end

  root "pages#home"

  get "/erase", to: "recipes#erase"
  # get "/listar_modelos_gemini", to: "recipes#listar_modelos_gemini"

  resources :ingredients
  resources :recipes, only: [:index, :show, :new, :create, :update] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :recipes do
    resources :comments, only: [:create, :destroy]
  end

  resources :comments, only: [:destroy]
  resources :bookmarks, only: [:index, :new, :create, :show, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :comments, dependent: :destroy
  has_many :bookmarks
end

app/controllers/recipes_controller.rb
require 'faraday'
require 'json'

class RecipesController < ApplicationController

  def index
    ingredients_formated = current_user.ingredients.map { |ingredient| "#{ingredient.name} #{ingredient.quantity} #{ingredient.unit}/"}
    client = OpenAI::Client.new
    chatgpt_response = client.chat(parameters: {
      model: "gpt-4o",
      messages: [{
        role: "user",
        content: "Create 5 recipes using the following ingredients:\n\n        #{ingredients_formated.join}\n\n          The recipe should use this format bellow to display the 5 recipes:\n          - Recipe title:\n          - Ingredients list: (exactly as given all the ingredients)\n          - Preparation time:\n          - Servings:\n          - Step-by-step: (instructions with details for each step)\n\n          The message should return with the recipes separeted by $ Recipe title Ingredients list Preparation time Servings Step-by-step\n          "
      }]
    })

    response_content = chatgpt_response["choices"][0]["message"]["content"]

    if session[:recipes].present?
      @recipes_from_gpt = session[:recipes]
    else
      @recipes_from_gpt = extract_recipes(response_content)
      session[:recipes] = @recipes_from_gpt
    end

    Rails.logger.info "Structured Recipe: #{@recipes_from_gpt.inspect}"
  end

  def new
    @recipe = Recipe.new
  end

  def show
  end

  def erase
    @ingredients = current_user.ingredients
    @ingredients.each do |ingredient|
      ingredient.destroy
    end
    session.delete(:recipes)
    redirect_to bookmarks_path
  end

  def create

    params.require(:recipe_data).permit("Recipe title", "Preparation time", "Servings", "Step-by-step")
    @recipe = Recipe.new()
    @recipe.title = params[:recipe_data]["Recipe title"]
    @recipe.prep_time = params[:recipe_data]["Preparation time"]
    @recipe.servings = params[:recipe_data]["Servings"]
    @recipe.instructions = params[:recipe_data]["Step-by-step"]
    @recipe.done = params[:done] || false
    @recipe.save

    @bookmark = Bookmark.new(user: current_user, recipe: @recipe)
    @bookmark.save

    if @recipe.done == true
      redirect_to new_recipe_comment_path(@recipe)
    else
      flash[:alert]="Recipe saved in the history !"
      redirect_to request.referer
    end

  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    # No need for app/views/recipes/update.html.erb
    redirect_to new_recipe_comment_path(@recipe)
  end

  private

  def extract_recipes(content)
    raw_recipes = content.split("$").map(&:strip)
    raw_recipes[1..].map do |raw_recipe|
      {
        "Recipe title" => extract_value(raw_recipe, "Recipe title:"),
        "Ingredients list" => extract_ingredients(raw_recipe, "Ingredients list:"),
        "Preparation time" => extract_value(raw_recipe, "Preparation time:"),
        "Servings" => extract_value(raw_recipe, "Servings:"),
        "Step-by-step" => extract_steps(raw_recipe, "Step-by-step:")
      }
    end
  end

  def extract_value(content, key)
    match = content.match(/#{key}\s*(.*?)(?=\n\s*-|\z)/)
    match ? match[1].strip : nil
  end

  def extract_ingredients(content, key)
    match = content.match(/#{key}\s*(.*?)(?=\n\s*-|\z)/)
    if match
      ingredients = match[1].strip
      ingredients.split("\n").map { |ingredient| ingredient.gsub(/^- /, '').strip }.join(", ")
    else
      nil
    end
  end

  def extract_steps(content, key)
    match = content.match(/#{key}\s*(.*?)(?=\z)/m)
    match ? match[1].strip : nil
  end

  def recipe_params
    params.require(:recipe).permit(:title, :rating, :instructions, :prep_time, :done, :servings)
  end

end

app/views/recipes/edit.html.erb
edit recipe

app/views/recipes/index.html.erb
<div class="mb-3 p-4" style="background-color: #5edc9b; opacity: 1; display: flex; justify-content: center; align-items: center; position: relative; border-radius: 0 0 20px 20px;">

  <%= link_to ingredients_path, style: "position: absolute; left: 20px;" do %>
    <i class="fa-regular fa-circle-left fa-2xl" style="color: #000000;"></i>
  <% end %>

  <h1 class="text-center" style="margin: 0;">RECIPES SUGGESTIONS</h1>

</div>
    <div class="px-4 my-4">
      <div class="accordion" id="recipeAccordion">
        <!-- Recipes -->
        <% @recipes_from_gpt.each_with_index do |recipe, index| %>
          <div class="accordion-item border-top mb-3" style="border-radius: 15px !important" >
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button <%= 'collapsed' if index > 0 %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= index %>" aria-expanded="true" aria-controls="collapseOne" style="border-radius: 15px !important">
                <%= recipe["Recipe title"] %>
              </button>
            </h2>
            <div id="collapse_<%= index %>" class="accordion-collapse collapse <%= 'show' if index < 1 %>" aria-labelledby="heading_<%= index %>" data-bs-parent="#recipeAccordion">
              <div class="accordion-body">
                  <p><strong>Ingredients:</strong> <%= recipe["Ingredients list"] %></p>
                  <p><strong>Preparation Time:</strong> <%= recipe["Preparation time"] %></p>

                <%= link_to 'Let s do it!', recipe_path(1, recipe: recipe), class:"btn btn-success btn-sm rounded-pill" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/recipes/new.html.erb
<h1>NEW RECIPE</h1>

app/views/recipes/show.html.erb
  <%# -------------------- Header ------------------ %>

<div class="mb-3 p-4" style="background-color: #5edc9b; opacity: 1; display: flex; justify-content: center; align-items: center; position: relative; border-radius: 0 0 20px 20px;">

  <%= link_to recipes_path, style: "position: absolute; left: 20px;" do %>
    <i class="fa-regular fa-circle-left fa-2xl" style="color: #000000;"></i>
  <% end %>

  <h1 class="text-center" style="margin: 0;">YOUR RECIPE</h1>

</div>


  <%# -------------------- Display recipe ------------------ %>

<div class="border m-3 p-3 bg-light" style="border-radius: 15px !important">
  <p class="text-center fs-4 border-bottom pb-2"><strong><%= params["recipe"]["Recipe title"] %></strong></p>
  <p><i class="fa-solid fa-stopwatch fa-lg m-2"></i> <%= params["recipe"]["Preparation time"] %></p>
  <p><i class="fa-solid fa-utensils fa-lg m-2"></i><%= params["recipe"]["Servings"]%></p>
  <p><strong>Step-by-step:</strong></p><% params["recipe"]["Step-by-step"].split(/\n/).each do |instruction| %>
        <li> <%=instruction %></li>
    <% end %>
</div>


  <%# -------------------- Buttons ------------------ %>

<div class="d-flex justify-content-center">

<%= button_to 'I did it!',
  { controller: "recipes",
    action: "create",
    recipe_data: params.require(:recipe).permit("Recipe title", "Preparation time", "Servings", "Step-by-step"),
    done: true },
  method: :post,
  class: "btn btn-success mx-1 rounded-pill",
  data: { turbo: true } %>



<%= button_to 'Save it for later',
  { controller: "recipes",
    action: "create",
    recipe_data: params.require(:recipe).permit("Recipe title", "Preparation time", "Servings", "Step-by-step"),
    done: false },
  method: :post,
  class: "btn btn-success mx-1 rounded-pill" %>

</div>