config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "bookmarks#index", as: :authenticated_root
  end

  root "pages#home"

  get "/erase", to: "recipes#erase"
  # get "/listar_modelos_gemini", to: "recipes#listar_modelos_gemini"

  resources :ingredients
  resources :recipes, only: [:index, :show, :new, :create, :update] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :recipes do
    resources :comments, only: [:create, :destroy]
  end

  resources :comments, only: [:destroy]
  resources :bookmarks, only: [:index, :new, :create, :show, :destroy]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  scope :ordered, -> { order(id: :desc) }

  belongs_to :user
  validates :name, presence: true
  validates :quantity, presence: true

  validates :quantity, numericality: { greater_than: 0 }, if: :quantity_present?

  private

  def quantity_present?
    quantity.present?
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.ordered

  end

  def new
    @ingredient = Ingredient.new
    # @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user = current_user
    if @ingredient.save
      respond_to do |format|
        format.html { redirect_to ingredients_path, notice: "ingredient was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path, notice: "ingredient was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_path, notice: "ingredient was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :quantity, :unit)
  end
end

app/views/ingredients/_form.html.erb
<%= simple_form_for [@recipe, @ingredient],
  html: { class: "ingredient form d-flex flex-column ",
  data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } } do |f| %>

  <div class="">
    <%= f.input :name, input_html: { class: "form-control", style: "flex: 1; border-radius: 6px" }, label: "Name", label_html: { class: "text-white" } %>

    <div class="d-flex">
      <div class="me-3">
        <%= f.input :quantity, input_html: { class: "form-control", style: "flex: 0.5; border-radius: 6px" }, label: "Quantity", label_html: { class: "text-white" } %>
      </div>
      <%= f.input :unit,
        collection: ["Unit","Kg", "g", "L", "mL"],
        include_blank: " ",
        label: "Unit",
        label_html: { class: "text-white" },
        input_html: { class: "form-control", style: "flex: 0.75; border-radius: 6px" } %>
      </div>
    </div>

  <div class="d-flex justify-content-start mb-3">
    <%= link_to ingredients_path, class: "btn btn-secondary mx-3 rounded-pill" do %>
      <i class="fa-solid fa-xmark"></i>
    <% end %>
    <%= button_tag class: "btn btn-success rounded-pill" do %>
      <i class="fa-solid fa-check"></i>
    <% end %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div class="row">

  <%= turbo_frame_tag "ingredient_#{ingredient.id}" do %>
    <div class="ingredient bg-light mb-1 p-2 d-flex align-items-center justify-content-between rounded-5" style="border-bottom: 1px solid #DEE2E6;">

      <div class="badge rounded-pill badge-custom" style="min-width: 100px;">
        <%= ingredient.name %>
      </div>

      <div class="badge rounded-pill badge-light" style="width: 50px; display: flex; align-items: center; justify-content: center;">
        <%= ingredient.quantity %> <%= ingredient.unit %>
      </div>

      <div class="ingredient__actions d-flex">
        <%= button_to "",
          ingredient_path(ingredient),
          method: :delete,
          data: { turbo_method: :delete },
          class: "btn btn--light fa-regular fa-trash-can"%>
        <%= link_to "",
          edit_ingredient_path(ingredient),
          class: "btn btn--light fa-regular fa-pen-to-square ms-2" %>
      </div>
    </div>
  <% end %>

</div>

app/views/ingredients/create.turbo_stream.erb
<%= turbo_stream.prepend "ingredients", @ingredient %>
<%= turbo_stream.update Ingredient.new, ""%>

app/views/ingredients/destroy.turbo_stream.erb
<%= turbo_stream.remove "ingredient_#{@ingredient.id}" %>

app/views/ingredients/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to ingredient"), ingredient_path(@ingredient) %>

  <div class="header">
    <h1>Edit ingredient</h1>
  </div>

  <%= turbo_frame_tag "ingredient_#{@ingredient.id}" do %>
    <%= render "form", ingredient: @ingredient %>
  <% end %>
</main>

app/views/ingredients/index.html.erb
<div class="mb-3 p-4" style="background-color: #5edc9b; opacity: 1; display: flex; justify-content: center; align-items: center; position: relative; border-radius: 0 0 20px 20px;">


  <%= link_to bookmarks_path, style: "position: absolute; left: 20px;" do %>
    <i class="fa-regular fa-circle-left fa-2xl" style="color: #000000;"></i>
  <% end %>

  <h1 class="text-center" style="margin: 0;">WHAT TO COOK ?</h1>

</div>


<div class="container-fluid">


  <div class="card-category" style="background-color: #fd8442;">
    <h2>Ingredients in your kitchen</h2>
  </div>

  <div class="card-ingredients">
    <div>
      <%= link_to "+ ingredient",
          new_ingredient_path,
          class: "btn btn-primary my-3 rounded-pill box-shadow",
          data: { turbo_frame: :new_ingredient},
          style: "opacity: 1; background-color: #21aade; border: 3px solid #dbcbb3;" %>
    </div>

    <%= turbo_frame_tag :new_ingredient %>

    <%= turbo_frame_tag "ingredients" do %>
      <%= render @ingredients %>
    <% end %>
  </div>

    <div style="display: flex; flex-direction: column; align-items: center;">
      <div data-controller="recipe-request" class="btn mb-1 mt-3 rounded-pill box-shadow" style="opacity: 1; background-color: #fd8442; border: 3px solid #dbcbb3;">
        <%= link_to "Let's Cook", recipes_path, data: {action: "click->recipe-request#handleClick"} %>
      </div>
    </div>
</div>

app/views/ingredients/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to ingredients"), ingredients_path %>

  <div class="header">
    <h1>New ingredient</h1>
  </div>

  <%= turbo_frame_tag @ingredient do %>
    <%= render "form", ingredient: @ingredient %>
  <% end %>
</main>

app/views/ingredients/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to ingredients"), ingredients_path %>
  <div class="header">
    <h1>
      <%= @ingredient.name %>
    </h1>
  </div>
</main>